"""Add parent_id to category for nesting

Revision ID: e856f8d1aeeb
Revises: 
Create Date: 2025-07-12 21:55:07.887827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e856f8d1aeeb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('_parent_category_name_uc', ['parent_id', 'name'])
        batch_op.create_foreign_key(batch_op.f('fk_categories_parent_id_categories'), 'categories', ['parent_id'], ['id'])

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_ingredients_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_ingredients_name'), type_='unique')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_categories_parent_id_categories'), type_='foreignkey')
        batch_op.drop_constraint('_parent_category_name_uc', type_='unique')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
